# Generated by Django 5.1.5 on 2025-01-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostup_course', models.CharField(max_length=250)),
                ('modul', models.TextField()),
                ('material', models.TextField()),
                ('description4', models.TextField()),
                ('description5', models.TextField()),
                ('about_description', models.TextField()),
                ('image_prepod', models.ImageField(upload_to='course_img/')),
                ('full_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('image_client', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dostup', models.CharField(max_length=255)),
                ('count_lesson', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_about_master_class', models.TextField()),
                ('image_master', models.ImageField(upload_to='master_class_images/')),
                ('position', models.CharField(max_length=255)),
                ('description_process', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='statya_images/')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_num', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_classes', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammaMasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_master', models.CharField(max_length=255)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programma_master_classes', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Keys2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=255)),
                ('statya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_statya2', to='web_site.statya')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('statya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_statya', to='web_site.statya')),
            ],
        ),
        migrations.CreateModel(
            name='WhoForCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_for_course', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='YouLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_learns', to='web_site.cours')),
            ],
        ),
    ]
