# Generated by Django 5.1.5 on 2025-01-19 19:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description1_ru', models.TextField(blank=True, null=True)),
                ('description1_ky', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description2_ru', models.TextField(blank=True, null=True)),
                ('description2_ky', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('description3_ru', models.TextField(blank=True, null=True)),
                ('description3_ky', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dostup_course', models.CharField(max_length=250)),
                ('dostup_course_ru', models.CharField(max_length=250, null=True)),
                ('dostup_course_ky', models.CharField(max_length=250, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('description4_ru', models.TextField(blank=True, null=True)),
                ('description4_ky', models.TextField(blank=True, null=True)),
                ('description5', models.TextField(blank=True, null=True)),
                ('description5_ru', models.TextField(blank=True, null=True)),
                ('description5_ky', models.TextField(blank=True, null=True)),
                ('image_prepod', models.ImageField(upload_to='course_img/')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name_ky', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('position_ky', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('dostup', models.CharField(blank=True, max_length=255, null=True)),
                ('dostup_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('dostup_ky', models.CharField(blank=True, max_length=255, null=True)),
                ('count_lesson', models.CharField(max_length=50)),
                ('count_lesson_ru', models.CharField(max_length=50, null=True)),
                ('count_lesson_ky', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_about_master_class', models.TextField(blank=True, null=True)),
                ('description_about_master_class_ru', models.TextField(blank=True, null=True)),
                ('description_about_master_class_ky', models.TextField(blank=True, null=True)),
                ('image_master', models.ImageField(blank=True, null=True, upload_to='master_class_images/')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('position_ky', models.CharField(blank=True, max_length=255, null=True)),
                ('description_process', models.TextField(blank=True, null=True)),
                ('description_process_ru', models.TextField(blank=True, null=True)),
                ('description_process_ky', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='statya_images/')),
                ('for_key_description', models.TextField(blank=True, null=True)),
                ('for_key_description_ru', models.TextField(blank=True, null=True)),
                ('for_key_description_ky', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description1_ru', models.TextField(blank=True, null=True)),
                ('description1_ky', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description2_ru', models.TextField(blank=True, null=True)),
                ('description2_ky', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('description3_ru', models.TextField(blank=True, null=True)),
                ('description3_ky', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_status', models.CharField(choices=[('месяц +', 'месяц +'), ('год', 'год'), ('год+', 'год+')], default='месяц +', max_length=32)),
                ('tariff_pay', models.CharField(choices=[('Ежемесячно', 'Ежемесячно'), ('Ежегодно', 'Ежегодно')], default='Ежемесячно', max_length=32)),
                ('status', models.CharField(choices=[('Начальная', 'Начальная'), ('Про', 'Про')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fio', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('gender_status', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=32, null=True, verbose_name='Пол')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_user')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_course', to='web_site.cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='кол-во модулей - кол-во материалов', max_length=32)),
                ('material_ru', models.CharField(help_text='кол-во модулей - кол-во материалов', max_length=32, null=True)),
                ('material_ky', models.CharField(help_text='кол-во модулей - кол-во материалов', max_length=32, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='into_course', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web_site.cart')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_item', to='web_site.cours')),
                ('master_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_class_item', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_ky', models.CharField(max_length=255, null=True)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_num', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_classes', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Process_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('title_ky', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_pl', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammaMasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_master', models.CharField(max_length=255)),
                ('name_master_ru', models.CharField(max_length=255, null=True)),
                ('name_master_ky', models.CharField(max_length=255, null=True)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programma_master_classes', to='web_site.masterclass')),
            ],
        ),
        migrations.CreateModel(
            name='Keys2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=255)),
                ('keys_ru', models.CharField(max_length=255, null=True)),
                ('keys_ky', models.CharField(max_length=255, null=True)),
                ('statya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_statya2', to='web_site.statya')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('key_ru', models.CharField(max_length=255, null=True)),
                ('key_ky', models.CharField(max_length=255, null=True)),
                ('statya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys_statya', to='web_site.statya')),
            ],
        ),
        migrations.CreateModel(
            name='TariffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('info_ru', models.CharField(max_length=100, null=True)),
                ('info_ky', models.CharField(max_length=100, null=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_info', to='web_site.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='VisaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_cart', models.CharField(help_text='Введите номер банковской карты', max_length=16, validators=[django.core.validators.RegexValidator('\\d{16}$', message='Введите все цифры карты')])),
                ('graduation_date', models.DateField()),
                ('csv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodpiskiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srok', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podpiski_user', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podpiski_tariff', to='web_site.tariff')),
                ('visa_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podpiska', to='web_site.visacart')),
            ],
        ),
        migrations.CreateModel(
            name='WhoForCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_ru', models.CharField(max_length=500, null=True)),
                ('name_ky', models.CharField(max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_for_course', to='web_site.cours')),
            ],
        ),
        migrations.CreateModel(
            name='YouLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_ru', models.CharField(max_length=500, null=True)),
                ('name_ky', models.CharField(max_length=500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_learns', to='web_site.cours')),
            ],
        ),
    ]
